language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
- openjdk6
deploy:
  provider: heroku
  api_key:
    secure: Qr7c7U78rITtxWMfcjNrpew6CSZlDJvSDtab7TS2ljQ/oidny4RQOdhj6v8LJRUqiRxm7x1dZcpyCl2SyQb7MLDkDPf9Zbf5MSJRE9upGGzT/hEwi5tsLJVRNdosY+RaGbom2zLQvZ+ILGq78Fot9s149aAGQZUc/OzwPGDTQLU=
