language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
- openjdk6
deploy:
  provider: heroku
  api_key:
    secure: NGst6pgfG3g+b9VvKx4uzc03weeQb20i9Gicl1Y5ztPJiRRH3Q+d76ufP61L/AmmN000fO2pZ5p9HQGGJDxMq0Of+xDTxaqc7VjtT6lxsBj5m+ThF5vQ0rYN4Wo7hCZ1eLK88LbLxc8TVH2C1GnWVXj67d8ROs+AzrEZAIwolkw=
