language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
- openjdk6
deploy:
  provider: heroku
  api_key:
    secure: NreCMvLcq6upCl/5ZqEeBC60TnBiE7g+Lu+6917sxQ+m2nzkUA7QTQN167qbjhF6itJm7+sV0VOqYoK1xNz2KTOSPaw/LugJmxbZkMSDwxAZ4sHlfY09Cq7UNOaDOverFoWHrrGNJugS1RIl3ZBtitMkBK69CAdfYyG4SCVb7A4=
  app: spheretestclient
  on:
    repo: rennersebastian/spheretestclient
